import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import Header from "./_components/Header";

import "./globals.css";

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} font-fredoka antialiased mx-auto`}>
        <Header />
        <div className="container mx-auto my-8 px-4">{children}</div>
      </body>
    </html>
  );
}
